=== horanek-david/L3N7UO_XMLGyak/L3N7UO_1006/HD_ertoxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="document">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="A" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Ab" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Abx" type="xs:string"/>
										<xs:element name="Aby" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Ac">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Acd" type="xs:string"/>
										<xs:element name="Ace" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Aa" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="B" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Bb">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Bbx" type="xs:string"/>
										<xs:element name="Bby" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Ba" type="xs:int" use="required"/>
						<xs:attribute name="Bc" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="C">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Cb" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="Ca" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="A_B">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="A_Bc" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="A_B_a" type="xs:int" use="required"/>
						<xs:attribute name="A_B_b" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		
		<xs:key name="K1">
			<xs:selector xpath="A"/>
			<xs:field xpath="@Aa"/>
		</xs:key>
		
		<xs:key name="K2">
			<xs:selector xpath="B"/>
			<xs:field xpath="@Ba"/>
		</xs:key>
		
		<xs:keyref refer="K1" name="K11">
			<xs:selector xpath="A_B"></xs:selector>
			<xs:field xpath="@A_Bc"></xs:field>
		</xs:keyref>
		
		<xs:keyref refer="K2" name="K21">
			<xs:selector xpath="A_B"></xs:selector>
			<xs:field xpath="@A_Bc"></xs:field>
		</xs:keyref>
		
	</xs:element>
</xs:schema>

=== horanek-david/L3N7UO_XMLGyak/L3N7UO_1006/HD_xsdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE document>

<document xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="HD_ertoxsd.xsd">
	<A Aa="1">
		<Ab>
			<Abx>AX1</Abx>
			<Aby>AY1</Aby>
		</Ab>
		<Ab>
			<Abx>AX2</Abx>
			<Aby>AY2</Aby>
		</Ab>
		<Ac>
			<Acd>D</Acd>
			<Ace>E</Ace>
		</Ac>
	</A>
	<B Ba="1" Bc="1">
		<Bb>
			<Bbx>BX</Bbx>
			<Bby>BY</Bby>
		</Bb>
	</B>
	<C Ca="1">
		<Cb>B</Cb>
	</C>
	<A_B A_B_a="1" A_B_b="1">
		<A_Bc>C</A_Bc>
	</A_B>
</document>
