=== horanek-david/L3N7UO_XMLGyak/L3N7UO_0929/HD_konyv.dtd
<?xml version="1.0" encoding="UTF-8"?>

	<!ELEMENT konyvek (konyv+)>
		<!ELEMENT konyv (cim, kiadasiev, kiado, szerzo+, absztrakt?)>
			<!ELEMENT cim (#PCDATA)>
			<!ELEMENT kiadasiev (#PCDATA)>
			<!ELEMENT kiado (#PCDATA)>
			<!ELEMENT szerzo (#PCDATA)>
			<!ELEMENT absztrakt (#PCDATA)>
			<!ATTLIST konyv id ID #REQUIRED>

=== horanek-david/L3N7UO_XMLGyak/L3N7UO_0929/HD_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE konyvek SYSTEM "HD_konyv.dtd">

<konyvek>
	<konyv id="A1">
		<cim>A kis nyúl</cim>
		<kiadasiev>1996</kiadasiev>
		<kiado>Pesti kiadó</kiado>
		<szerzo>Kis Géza</szerzo>
		<szerzo>Nagy Endre</szerzo>
		<absztrakt/>
	</konyv>
	<konyv id="A2">
		<cim>Sárga Madár</cim>
		<kiadasiev>2012</kiadasiev>
		<kiado>Pesti kiadó</kiado>
		<szerzo>Barna Péter</szerzo>
		<absztrakt>a</absztrakt>
	</konyv>
	<konyv id="A3">
		<cim>Az ember</cim>
		<kiadasiev>1878</kiadasiev>
		<kiado>Kis kiadó</kiado>
		<szerzo>Fekete Andrea</szerzo>
		<absztrakt>a</absztrakt>
	</konyv>
</konyvek>
